version: "3"
services:
    web:
        build: .
        ports:
            - "8081:5000"
        depends_on:
            - mysql
        image: auth:latest
    mysql:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Test@123"
            ACCEPT_EULA: "Y"
