version: "3"
services:
    web:
        build: .
        ports:
            - "8082:5000"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Test@123"
            ACCEPT_EULA: "Y"
        ports: 
            - "3308:1433"
